modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="md" #mandatory
version="0.0.1-1.20.1" #mandatory
displayName="MonoDomatia" #mandatory
authors="YesMan" #optional
description='''Be careful where you step.'''
[[dependencies.md]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.md]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"